// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movie.Data;

namespace Movie.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "b4280b6a-0613-4cbd-a9e6-f1701e926e73",
                            ConcurrencyStamp = "81b0bb3e-9fc6-4ea7-8672-591c53fbd721",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "b4280b6a-0613-4cbd-a9e6-f1701e926e74",
                            ConcurrencyStamp = "b8c8a31f-9d7c-4f01-a1d9-4653470f3e60",
                            Name = "editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = "b4280b6a-0613-4cbd-a9e6-f1701e926e75",
                            ConcurrencyStamp = "a0e347bd-de2b-43e9-8d70-37ad1fc4b568",
                            Name = "guest",
                            NormalizedName = "GUEST"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "b4280b6a-0613-4cbd-a9e6-f1701e926e73",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c8554266-b401-4519-9aeb-a9283053fc58",
                            Email = "Test@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TEST@TEst.COM",
                            NormalizedUserName = "Test@TEST.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGt6WgjoPqLN1f++oJ5mbuBwHCXrlQZTeYYoda8+Id/mDrvLz7GA/dsZZwk9JLpdag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "Test@test.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "b4280b6a-0613-4cbd-a9e6-f1701e926e73",
                            RoleId = "b4280b6a-0613-4cbd-a9e6-f1701e926e73"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Movie.Entities.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("DateBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("PhotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Popularity")
                        .HasColumnType("bit");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(1500)")
                        .HasMaxLength(1500);

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Manhattan, New York City, New York, USA",
                            DateBirth = "April 4, 1965",
                            Gender = "Male",
                            Language = "English",
                            Name = "Robert Downey Jr.",
                            PhotoURL = "RobertDowneyJrPhoto.jpg",
                            Popularity = false,
                            ShortDescription = "Downey was born April 4, 1965 in Manhattan, New York, the son of writer, director and filmographer Robert Downey Sr. and actress Elsie Downey (née Elsie Ann Ford). Robert's father is of half Lithuanian Jewish, one quarter Hungarian Jewish, and one quarter Irish, descent, while Robert's mother was of English, Scottish, German, and Swiss-German ancestry."
                        },
                        new
                        {
                            Id = 2,
                            Country = "Washington, District of Columbia, USA",
                            DateBirth = "December 21, 1948",
                            Gender = "Male",
                            Language = "English",
                            Name = "Samuel L. Jackson",
                            PhotoURL = "SamuelJacksonPhoto.jpg",
                            Popularity = false,
                            ShortDescription = "Samuel L. Jackson is an American producer and highly prolific actor, having appeared in over 100 films, including Die Hard with a Vengeance (1995), Unbreakable (2000), Shaft (2000), Formula 51 (2001), Black Snake Moan (2006), Snakes on a Plane (2006), and the Star Wars prequel trilogy (1999-2005), as well as the Marvel Cinematic Universe."
                        },
                        new
                        {
                            Id = 3,
                            Country = "Sacramento, California, USA",
                            DateBirth = "October 1, 1989",
                            Gender = "Female",
                            Language = "English",
                            Name = "Brie Larson",
                            PhotoURL = "BrieLarsonPhoto.jpg",
                            Popularity = false,
                            ShortDescription = "Brie Larson has built an impressive career as an acclaimed television actress, rising feature film star and emerging recording artist. A native of Sacramento, Brie started studying drama at the early age of 6, as the youngest student ever to attend the American Conservatory Theater in San Francisco. She starred in one of Disney Channel's most watched original movies, Right on Track (2003), as well as the WB's Raising Dad (2001) and MGM's teen comedy Sleepover (2004) - all before graduating from middle school."
                        },
                        new
                        {
                            Id = 4,
                            Country = "Queens, New York City, New York, USA",
                            DateBirth = "October 19, 1966",
                            Gender = "Male",
                            Language = "English",
                            Name = "Jon Favreau",
                            PhotoURL = "JonFavreauPhoto.jpg",
                            Popularity = false,
                            ShortDescription = "The amiable, husky-framed actor with the tight, crinkly hair was born in Queens, New York on October 19, 1966, the only child of Madeleine (Balkoff), an elementary school teacher, and Charles Favreau, a special education teacher. His father has French-Canadian, German, and Italian ancestry, and his mother was from a Russian Jewish family. He attended the Bronx High School of Science before furthering his studies at Queens College in 1984. Dropping out just credits away from receiving his degree, Jon moved to Chicago where he focused on comedy and performed at several Chicago improvisational theaters, including the ImprovOlympic and the Improv Institute. He also found a couple of bit parts in films."
                        },
                        new
                        {
                            Id = 5,
                            Country = "Boston, Massachusetts, USA",
                            DateBirth = "April 2, 1962",
                            Gender = "Male",
                            Language = "English",
                            Name = "Clark Gregg",
                            PhotoURL = "ClarkGreggPhoto.jpg",
                            Popularity = false,
                            ShortDescription = "Clark Gregg was born on April 2, 1962 in Boston, Massachusetts, USA as Robert Clark Gregg. He is an actor and director, known for The Avengers (2012), Agents of S.H.I.E.L.D. (2013) and The New Adventures of Old Christine (2006)."
                        },
                        new
                        {
                            Id = 6,
                            Country = "Harlesden, London, England, UK",
                            DateBirth = "May 27, 1971",
                            Gender = "Male",
                            Language = "English",
                            Name = "Paul Bettany",
                            PhotoURL = "PaulBettanyPhoto.jpg",
                            Popularity = false,
                            ShortDescription = "Paul Bettany is an English actor. He first came to the attention of mainstream audiences when he appeared in the British film Gangster No. 1 (2000), and director Brian Helgeland's film A Knight's Tale (2001). He has gone on to appear in a wide variety of films, including A Beautiful Mind (2001), Master and Commander: The Far Side of the World (2003), Dogville (2003), Wimbledon (2004), and the adaptation of the novel The Da Vinci Code (2006). He is also known for his voice role as J.A.R.V.I.S. in the Marvel Cinematic Universe, specifically the films Iron Man (2008), Iron Man 2 (2010), The Avengers (2012), Iron Man 3 (2013), and Avengers: Age of Ultron (2015), in which he also portrayed the Vision, for which he garnered praise. He reprised his role as the Vision in Captain America: Civil War (2016)."
                        },
                        new
                        {
                            Id = 7,
                            Country = "Los Angeles, California, USA",
                            DateBirth = "September 27, 1972",
                            Gender = "Female",
                            Language = "English",
                            Name = "Gwyneth Paltrow",
                            PhotoURL = "GwynethPaltrowPhoto.jpg",
                            Popularity = false,
                            ShortDescription = "A tall, wafer thin, delicate beauty, Gwyneth Kate Paltrow was born in Los Angeles, the daughter of noted producer and director Bruce Paltrow and Tony Award-winning actress Blythe Danner. Her father was from a Jewish family, while her mother is of mostly German descent. When Gwyneth was eleven, the family moved to Massachusetts, where her father began working in summer stock productions in the Berkshires."
                        },
                        new
                        {
                            Id = 8,
                            Country = "Chicago, Illinois, USA",
                            DateBirth = "March 11, 1969",
                            Gender = "Male",
                            Language = "English",
                            Name = "Terrence Howard",
                            PhotoURL = "TerrenceHowardPhoto.jfif",
                            Popularity = false,
                            ShortDescription = "Terrence Howard was born in Chicago, Illinois, to Anita Jeanine Williams (née Hawkins) and Tyrone Howard. He was raised in Cleveland, Ohio. His love for acting came naturally, through summers spent with his great-grandmother, New York stage actress Minnie Gentry. He later began his acting career after being discovered on a New York City street by a casting director. Soon, he followed with several notable TV appearances on shows such as Living Single (1993), NYPD Blue (1993) and Soul Food (2000). He became well known for his lead role in the UPN TV series Sparks (1996)."
                        },
                        new
                        {
                            Id = 9,
                            Country = "Los Angeles, California, USA",
                            DateBirth = "December 4, 1949",
                            Gender = "Male",
                            Language = "English",
                            Name = "Jeff Bridges",
                            PhotoURL = "JeffBridgesPhoto.jpg",
                            Popularity = false,
                            ShortDescription = "Jeffrey Leon Bridges was born on December 4, 1949 in Los Angeles, California, the son of well-known film and TV star Lloyd Bridges and his long-time wife Dorothy Dean Bridges (née Simpson). He grew up amid the happening Hollywood scene with big brother Beau Bridges. Both boys popped up, without billing, alongside their mother in the film The Company She Keeps (1951), and appeared on occasion with their famous dad on his popular underwater TV series Sea Hunt (1958) while growing up."
                        },
                        new
                        {
                            Id = 10,
                            Country = "Hammersmith, London, England, UK",
                            DateBirth = "July 19, 1976",
                            Gender = "Male",
                            Language = "English",
                            Name = "Benedict Cumberbatch",
                            PhotoURL = "BenedictCumberbatchPhoto.jpg",
                            Popularity = false,
                            ShortDescription = "Benedict Timothy Carlton Cumberbatch was born and raised in London, England. His parents, Wanda Ventham and Timothy Carlton (born Timothy Carlton Congdon Cumberbatch), are both actors. He is a grandson of submarine commander Henry Carlton Cumberbatch, and a great-grandson of diplomat Henry Arnold Cumberbatch CMG."
                        },
                        new
                        {
                            Id = 11,
                            Country = "New York City",
                            DateBirth = "July 6, 1946",
                            Gender = "Male",
                            Language = "English",
                            Name = "Sylvester Stallone",
                            PhotoURL = "SylvesterStallonePhoto.jpg",
                            Popularity = false,
                            ShortDescription = "Sylvester Stallone is a athletically built, dark-haired American actor/screenwriter/director/producer, the movie fans worldwide have been flocking to see Stallone's films for over 40 years, making \"Sly\" one of Hollywood's biggest-ever box office draws."
                        },
                        new
                        {
                            Id = 12,
                            Country = "Los Angeles, California",
                            DateBirth = "November 11, 1974",
                            Gender = "Male",
                            Language = "English",
                            Name = "Leonardo Di Caprio",
                            PhotoURL = "LeonardoDiCaprioPhoto.jfif",
                            Popularity = true,
                            ShortDescription = "Few actors in the world have had a career quite as diverse as Leonardo DiCaprio's. DiCaprio has gone from relatively humble beginnings, as a supporting cast member of the sitcom Growing Pains (1985) and low budget horror movies."
                        },
                        new
                        {
                            Id = 13,
                            Country = "Syracuse, New York, USA",
                            DateBirth = "July 3, 1962",
                            Gender = "Male",
                            Language = "English",
                            Name = "Tom Cruse",
                            PhotoURL = "TomCrusePhoto.jpg",
                            Popularity = false,
                            ShortDescription = "In 1976, if you had told fourteen-year-old Franciscan seminary student Thomas Cruise Mapother IV that one day in the not too distant future he would be Tom Cruise, one of the top 100 movie stars of all time, he would have probably grinned and told you that his ambition was to join the priesthood. Nonetheless, this sensitive, deeply religious youngster who was born in 1962 in Syracuse, New York, was destined to become one of the highest paid and most sought after actors in screen history."
                        },
                        new
                        {
                            Id = 14,
                            Country = "Thal, Styria, Austria",
                            DateBirth = "July 30, 1947",
                            Gender = "Male",
                            Language = "English",
                            Name = "Arnold Schwarcneger",
                            PhotoURL = "ArnoldSchwarcnegerPhoto.jpg",
                            Popularity = false,
                            ShortDescription = "With an almost unpronounceable surname and a thick Austrian accent, who would have ever believed that a brash, quick talking bodybuilder from a small European village would become one of Hollywood's biggest stars, marry into the prestigious Kennedy family, amass a fortune via shrewd investments and one day be the Governor of California!"
                        },
                        new
                        {
                            Id = 15,
                            Country = "New York City, New York, USA",
                            DateBirth = "October 5, 1983",
                            Gender = "Male",
                            Language = "English",
                            Name = "Jesse Eisenberg",
                            PhotoURL = "JesseEisenbergPhoto.jpg",
                            Popularity = false,
                            ShortDescription = "Curly haired and with a fast-talking voice, Jesse Eisenberg is a movie actor, known for his Academy Award nominated role as Mark Zuckerberg in the 2010 film The Social Network. He has also starred in the films The Squid and the Whale, Adventureland, The Education of Charlie Banks, 30 Minutes or Less, Now You See Me and Zombieland."
                        },
                        new
                        {
                            Id = 16,
                            Country = "Pittsburgh, Pennsylvania, USA",
                            DateBirth = "May 1, 1972",
                            Gender = "Female",
                            Language = "English",
                            Name = "Julie Benz",
                            PhotoURL = "JulieBenzPhoto.jpg",
                            Popularity = false,
                            ShortDescription = "Julie Benz was born in Pittsburgh, Pennsylvania, USA on May 1, 1972. Julie's father is a Pittsburgh surgeon and her mother is a figure skater. The family settled in nearby Murrysville, when Julie was two, and she started ice skating at age three."
                        },
                        new
                        {
                            Id = 17,
                            Country = "West Bromwich, West Midlands, England, UK",
                            DateBirth = "March 3, 1973",
                            Gender = "Male",
                            Language = "English",
                            Name = "Matthew Marsden",
                            PhotoURL = "MatthewMarsdenPhoto.jpg",
                            Popularity = false,
                            ShortDescription = "British actor/singer/Producer Matthew Marsden began his acting career in the UK and rose to stardom from his role on the long-running ITV series Coronation Street (1960), as Chris Collins. He left the show to pursue a music and acting career in the US and hasn't looked back since."
                        },
                        new
                        {
                            Id = 18,
                            Country = "Reading, Berkshire, England, UK",
                            DateBirth = "October 5, 1975",
                            Gender = "Female",
                            Language = "English",
                            Name = "Kate Winslet",
                            PhotoURL = "KateWinsletPhoto.jpg",
                            Popularity = false,
                            ShortDescription = "Ask Kate Winslet what she likes about any of her characters, and the word \"ballsy\" is bound to pop up at least once. The British actress has made a point of eschewing straightforward pretty-girl parts in favor of more devilish damsels; as a result, she's built an eclectic resume that runs the gamut from Shakespearean tragedy to modern-day"
                        },
                        new
                        {
                            Id = 19,
                            Country = "Chicago, Illinois, USA",
                            DateBirth = "February 24, 1966",
                            Gender = "Male",
                            Language = "English",
                            Name = "Billy Zane",
                            PhotoURL = "BillyZanePhoto.jpg",
                            Popularity = false,
                            ShortDescription = "William George Zane, better known as Billy Zane, was born on February 24, 1966 in Chicago, Illinois, to Thalia (Colovos) and William Zane, both of Greek ancestry. His parents were amateur actors and managed a medical technical school. Billy has an older sister, actress and singer Lisa Zane. Billy was bitten by the acting bug early on."
                        },
                        new
                        {
                            Id = 20,
                            Country = "West Covina, California, USA",
                            DateBirth = "October 16, 1958",
                            Gender = "Male",
                            Language = "English",
                            Name = "Tim Robbins",
                            PhotoURL = "https://m.media-amazon.com/images/M/MV5BMTI1OTYxNzAxOF5BMl5BanBnXkFtZTYwNTE5ODI4._V1_UY1200_CR151,0,630,1200_AL_.jpg",
                            Popularity = false,
                            ShortDescription = "Born in West Covina, California, but raised in New York City, Tim Robbins is the son of former The Highwaymen singer Gil Robbins and actress Mary Robbins (née Bledsoe). Robbins studied drama at UCLA, where he graduated with honors in 1981."
                        },
                        new
                        {
                            Id = 21,
                            Country = "Newport Beach, California, USA",
                            DateBirth = "July 9, 1957",
                            Gender = "Male",
                            Language = "English",
                            Name = "Kelly McGillis",
                            PhotoURL = "https://m.media-amazon.com/images/M/MV5BMjA0OTg5ODY3Ml5BMl5BanBnXkFtZTgwNzkxOTU3MDI@._V1_.jpg",
                            Popularity = false,
                            ShortDescription = "Kelly Ann McGillis was born in Newport Beach, California, to Virginia Joan (Snell), a homemaker, and Donald Manson McGillis, a general practitioner of medicine. She has English, Welsh, Scots-Irish, and German ancestry."
                        },
                        new
                        {
                            Id = 22,
                            Country = "Los Angeles, California",
                            DateBirth = "November 11, 1974",
                            Gender = "Male",
                            Language = "English",
                            Name = "Leonardo DiCaprio",
                            PhotoURL = "LeonardoDiCaprioPhoto.jfif",
                            Popularity = true,
                            ShortDescription = "Few actors in the world have had a career quite as diverse as Leonardo DiCaprio's. DiCaprio has gone from relatively humble beginnings, as a supporting cast member of the sitcom Growing Pains (1985) and low budget horror movies."
                        });
                });

            modelBuilder.Entity("Movie.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Action"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Crime"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Adventure"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Drama"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Fantasy"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Thriller"
                        },
                        new
                        {
                            ID = 8,
                            Name = "General"
                        },
                        new
                        {
                            ID = 9,
                            Name = "Horror"
                        },
                        new
                        {
                            ID = 10,
                            Name = "Comedy"
                        },
                        new
                        {
                            ID = 11,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            ID = 12,
                            Name = "Biography"
                        },
                        new
                        {
                            ID = 13,
                            Name = "Mystery"
                        },
                        new
                        {
                            ID = 14,
                            Name = "Uncategorised"
                        });
                });

            modelBuilder.Entity("Movie.Entities.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("DateBirth")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Belfast, Northern Ireland, UK",
                            DateBirth = "December 10, 1960",
                            Name = "Kenneth Branagh"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            DateBirth = "July 6, 1946",
                            Name = "Sylvester Stallone"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Kapusaksing, Ontario, Canada",
                            DateBirth = "August 16, 1954",
                            Name = "James Cameron"
                        },
                        new
                        {
                            Id = 4,
                            Country = "North Shields, Northumberland, England, UK",
                            DateBirth = "June 21, 1944",
                            Name = "Tony Scott"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Ireland",
                            DateBirth = "2012",
                            Name = "Pixar"
                        },
                        new
                        {
                            Id = 6,
                            Country = "London, England, UK",
                            DateBirth = "1958",
                            Name = "Iain Softley"
                        },
                        new
                        {
                            Id = 7,
                            Country = "Denver, Colorado, USA",
                            DateBirth = "August 28, 1962",
                            Name = "David Fincher"
                        },
                        new
                        {
                            Id = 8,
                            Country = "Bergen, Norway",
                            DateBirth = "May 19, 1967",
                            Name = "Morten Tyldum"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Olten, Switzerland",
                            DateBirth = "April 18, 1978",
                            Name = "Baran bo Odar"
                        },
                        new
                        {
                            Id = 10,
                            Country = "London, England, UK",
                            DateBirth = "July 30, 1970",
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 11,
                            Country = "USA",
                            DateBirth = "",
                            Gender = "Male",
                            Name = "Joe Russo",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 12,
                            Country = "USA",
                            DateBirth = "",
                            Gender = "Male",
                            Name = "Anthony Russo",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 13,
                            Country = "USA",
                            DateBirth = "",
                            Gender = "Female",
                            Name = "Anna Boden",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 14,
                            Country = "USA",
                            DateBirth = "",
                            Gender = "Male",
                            Name = "Jon Favreau",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 15,
                            Country = "USA",
                            DateBirth = "",
                            Gender = "Male",
                            Name = "Shane Black",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 16,
                            Country = "USA",
                            DateBirth = "",
                            Gender = "Male",
                            Name = "Louis Leterrier",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 17,
                            Country = "USA",
                            DateBirth = "",
                            Gender = "Male",
                            Name = "Taika Waititi",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 18,
                            Country = "USA",
                            DateBirth = "",
                            Gender = "Male",
                            Name = "Alan Taylor",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 19,
                            Country = "USA",
                            DateBirth = "",
                            Gender = "Male",
                            Name = "Joss Whedon",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 20,
                            Country = "USA",
                            DateBirth = "",
                            Gender = "Male",
                            Name = "Joe Johnston",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 21,
                            Country = "USA",
                            DateBirth = "",
                            Gender = "Male",
                            Name = "James Gunn",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 22,
                            Country = "USA",
                            DateBirth = "",
                            Gender = "Male",
                            Name = "Peyton Reed",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 23,
                            Country = "USA",
                            DateBirth = "",
                            Gender = "Male",
                            Name = "Jon Watts",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 24,
                            Country = "USA",
                            DateBirth = "",
                            Gender = "Male",
                            Name = "Scott Derrickson",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 25,
                            Country = "USA",
                            DateBirth = "",
                            Gender = "Male",
                            Name = "Ryan Coogler",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 26,
                            Country = "Ireland",
                            DateBirth = "",
                            Gender = "Male",
                            Name = "Kenneth Branagh",
                            ShortDescription = ""
                        },
                        new
                        {
                            Id = 27,
                            Country = "USA",
                            DateBirth = "",
                            Gender = "Male",
                            Name = "Kevin Feige",
                            ShortDescription = ""
                        });
                });

            modelBuilder.Entity("Movie.Entities.MovieActor", b =>
                {
                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("ActorID")
                        .HasColumnType("int");

                    b.HasKey("MovieID", "ActorID");

                    b.HasIndex("ActorID");

                    b.ToTable("MovieActors");
                });

            modelBuilder.Entity("Movie.Entities.MovieCategory", b =>
                {
                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.HasKey("MovieID", "CategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("MovieCategories");
                });

            modelBuilder.Entity("Movie.Entities.Movies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActorNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categories")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<string>("DirectorName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Popularity")
                        .HasColumnType("bit");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<string>("PublisherName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(1500)")
                        .HasMaxLength(1500);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TrailerURL")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("WatchTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActorNames = "Sylvester Stallone,Julie Benz,Matthew Marsden",
                            Categories = "Action, Thriller",
                            Country = "Germany,USA,Thailand",
                            DirectorId = 2,
                            DirectorName = "Sylvester Stallone",
                            Language = "English, Burmese, Thai",
                            PhotoURL = "Rambo2008Image.jpg",
                            Popularity = false,
                            PublisherId = 2,
                            PublisherName = "Lionsgate",
                            Rating = 7.0,
                            ReleaseDate = "25 January 2008",
                            ShortDescription = "In Thailand, John Rambo joins a group of mercenaries to venture into war-torn Burma, and rescue a group of Christian aid workers who were kidnapped by the ruthless local infantry unit.",
                            Title = "Rambo",
                            WatchTime = "92min"
                        },
                        new
                        {
                            Id = 2,
                            ActorNames = "Leonardo Di Caprio,Kate Winslet,Billy Zane",
                            Categories = "Drama, Romance",
                            Country = "USA, Mexico, Australia, Canada",
                            DirectorId = 3,
                            DirectorName = "James Cameron",
                            Language = "English, Swedish, Italian, French",
                            PhotoURL = "Titanic1997Image.jpg",
                            Popularity = false,
                            PublisherId = 1,
                            PublisherName = "20th Century Fox",
                            Rating = 7.7999999999999998,
                            ReleaseDate = "19 December 1997",
                            ShortDescription = "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, Ill-fated R.M.S Titanic.",
                            Title = "Titanic",
                            WatchTime = "194min"
                        },
                        new
                        {
                            Id = 3,
                            ActorNames = "Tom Cruise,Tim Robbins,Kelly McGillis",
                            Categories = "Action, Drama",
                            Country = "USA",
                            DirectorId = 4,
                            DirectorName = "Tony Scott",
                            Language = "English",
                            PhotoURL = "TopGun1986Image.jpg",
                            Popularity = false,
                            PublisherId = 4,
                            PublisherName = "Paramount Pictures",
                            Rating = 6.9000000000000004,
                            ReleaseDate = "16 May 1986",
                            ShortDescription = "As students at the United States Navy's elite fighter weapons school compete to be best in the class, one daring young pilot learns a few things from a civilian instructor that are not taught in the classroom.",
                            Title = "Top Gun",
                            WatchTime = "110min"
                        },
                        new
                        {
                            Id = 4,
                            ActorNames = "Arnold Schwarcneger,Linda Hamilton,Michael Biehn",
                            Categories = "Action, Sci-Fi",
                            Country = "UK",
                            DirectorId = 3,
                            DirectorName = "James Cameron",
                            Language = "English",
                            PhotoURL = "TheTerminator1984Image.jpg",
                            Popularity = false,
                            PublisherId = 5,
                            PublisherName = "Cinema '84",
                            Rating = 8.0,
                            ReleaseDate = "26 October 1984",
                            ShortDescription = "A human soldier is sent from 2029 to 1984 to stop an almost indestructible cyborg killing machine, sent from the same year, which has been programmed to execute a young woman whose unborn son is the key to humanity's future salvation.",
                            Title = "The Terminator",
                            WatchTime = "107min"
                        },
                        new
                        {
                            Id = 5,
                            ActorNames = "Benedict Cumberbatch,Chiwetel Ejiofor,Rachel McAdams",
                            Categories = "Action, Adventure, Fanstasy",
                            Country = "USA",
                            DirectorId = 15,
                            DirectorName = "Scott Derrickson",
                            Language = "English",
                            PhotoURL = "DrStrange.jpg",
                            Popularity = false,
                            PublisherId = 11,
                            PublisherName = "Marvel Studios",
                            Rating = 7.5,
                            ReleaseDate = "4 November, 2016",
                            ShortDescription = "While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.",
                            Title = "Doctor Strange",
                            WatchTime = "115min"
                        },
                        new
                        {
                            Id = 6,
                            ActorNames = "Jesse Eisenberg,Andrew Garfield,Justin Timberlake,Rooney Mara",
                            Categories = "Drama, Biography",
                            Country = "USA",
                            DirectorId = 7,
                            DirectorName = "David Fincher",
                            Language = "English, French",
                            PhotoURL = "TheSocialNetwork2010Image.png",
                            Popularity = false,
                            PublisherId = 7,
                            PublisherName = "Columbia Pictures",
                            Rating = 7.7000000000000002,
                            ReleaseDate = "1 October 2010 ",
                            ShortDescription = "As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea, and by the co-founder who was later squeezed out of the business.",
                            Title = "The Social Network",
                            WatchTime = "120min"
                        },
                        new
                        {
                            Id = 7,
                            ActorNames = "Benedict Cumberbatch,Keira Knightley,Matthew Goode",
                            Categories = "Drama, Biography, Thriller",
                            Country = "UK, USA",
                            DirectorId = 8,
                            DirectorName = "Morten Tyldum",
                            Language = "English, German",
                            PhotoURL = "TheImitationGame2014Image.jpg",
                            Popularity = false,
                            PublisherId = 8,
                            PublisherName = "Black Bear Pictures",
                            Rating = 8.0,
                            ReleaseDate = "25 December 2014",
                            ShortDescription = "During World War II, the English mathematical genius Alan Turing tries to crack the German Enigma code with help from fellow mathematicians.",
                            Title = "The Imitation Game",
                            WatchTime = "114min"
                        },
                        new
                        {
                            Id = 8,
                            ActorNames = "Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,Tom Hardy,Dileep Rao,Cillian Murphy,Tom Berenger,Marion Cotillard,Michael Caine",
                            Categories = "Action, Adventure, Sci-Fi",
                            Country = "USA, UK",
                            DirectorId = 10,
                            DirectorName = "Christopher Nolan",
                            Language = "English, Japanese, French",
                            PhotoURL = "Inception2010Image.jpg",
                            Popularity = false,
                            PublisherId = 10,
                            PublisherName = "Legendary Entertainment",
                            Rating = 8.8000000000000007,
                            ReleaseDate = "16 July 2010",
                            ShortDescription = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
                            Title = "Inception",
                            WatchTime = "148min"
                        },
                        new
                        {
                            Id = 9,
                            ActorNames = "Brie Larson,Samuel L. Jackson,Clark Gregg",
                            Categories = "Action, Adventure, Sci-Fi",
                            Country = "USA",
                            DirectorId = 4,
                            DirectorName = "Anna Boden",
                            Language = "English",
                            PhotoURL = "CaptainMarvel.jpg",
                            Popularity = false,
                            PublisherId = 11,
                            PublisherName = "Marvel Studios",
                            Rating = 6.7999999999999998,
                            ReleaseDate = "March 8, 2019",
                            ShortDescription = "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.",
                            Title = "Captain Marvel",
                            WatchTime = "123min"
                        },
                        new
                        {
                            Id = 10,
                            ActorNames = "Robert Downey Jr.,Gwyneth Paltrow,Jon Favreau,Samuel L. Jackson,Jeff Bridges,Terrence Howard,Paul Bettany,Clark Gregg",
                            Categories = "Action, Adventure, Sci-Fi",
                            Country = "USA",
                            DirectorId = 5,
                            DirectorName = "Jon Favreau",
                            Language = "English",
                            PhotoURL = "IronMan.jpg",
                            Popularity = false,
                            PublisherId = 4,
                            PublisherName = "Paramount Pictures",
                            Rating = 7.9000000000000004,
                            ReleaseDate = "May 2, 2008",
                            ShortDescription = "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
                            Title = "Iron Man",
                            WatchTime = "126min"
                        });
                });

            modelBuilder.Entity("Movie.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Publisher");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Name = "20th Century Fox",
                            Year = "1935"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Vancouver, British Columbia",
                            Name = "Lionsgate",
                            Year = "July 10, 1997"
                        },
                        new
                        {
                            Id = 4,
                            Country = "USA",
                            Name = "Paramount Pictures",
                            Year = "1916"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Not known",
                            Name = "Cinema '84",
                            Year = "Not known"
                        },
                        new
                        {
                            Id = 6,
                            Country = "USA",
                            Name = "United Artists",
                            Year = "1919"
                        },
                        new
                        {
                            Id = 7,
                            Country = "USA",
                            Name = "Columbia Pictures",
                            Year = "1974"
                        },
                        new
                        {
                            Id = 8,
                            Country = "Santa Monica, California",
                            Name = "Black Bear Pictures",
                            Year = "2011"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Germany",
                            Name = "Wiedemann & Berg Film Production",
                            Year = "2003"
                        },
                        new
                        {
                            Id = 10,
                            Country = "USA",
                            Name = "Legendary Entertainment",
                            Year = "2000"
                        },
                        new
                        {
                            Id = 11,
                            Country = "USA",
                            Name = "Marvel Studios",
                            Year = "1996"
                        });
                });

            modelBuilder.Entity("Movie.Entities.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WishLists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Movie.Entities.MovieActor", b =>
                {
                    b.HasOne("Movie.Entities.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movie.Entities.Movies", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Movie.Entities.MovieCategory", b =>
                {
                    b.HasOne("Movie.Entities.Category", "Category")
                        .WithMany("MovieCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movie.Entities.Movies", "Movie")
                        .WithMany("MovieCategories")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Movie.Entities.Movies", b =>
                {
                    b.HasOne("Movie.Entities.Director", null)
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movie.Entities.Publisher", "Publisher")
                        .WithMany("Movies")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
